# Generated by Django 5.0 on 2023-12-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
