# Generated by Django 4.2.6 on 2024-01-01 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('books', '0002_bookmodel_category_bookmodel_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='category',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.categorymodel'),
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('post_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='books.bookmodel')),
            ],
        ),
    ]
